# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:			/:categories/:title:output_ext

# Setup
title:               Hojimat Consulting 
tagline:             'Statistical and Economic Consultancy'
description:         'I help researchers, data scientists and growth hackers in performing economic analyses, developing statistical algorithms and research methods. My two-edits policy guarantees the quality of my work and your satisfaction. Read on.'
url:                 'http://hojimat.com'
baseurl:             ''
plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]

# About/contact
author:
  name:              Ravshanbek Khodzhimatov
  url:               http://ravshansk.com
  email:             rsk@ravshansk.com

# Social media
twitter_username:	hojimat

# Custom vars
version:             1.0.0
